<?php
/**
 * Implementation of hook_perm().
 */
function privatemsg_extras_init() {
  drupal_add_css(drupal_get_path('module', 'privatemsg_extras') .'/privatemsg_extras.css', 'theme', 'all');
  drupal_add_js(drupal_get_path('module', 'privatemsg_extras') .'/privatemsg_extras.js');
}

/**
 * Implementation of hook_perm().
 */
function privatemsg_extras_perm() {
  return array('access privatemsg extras');
}

/**
 * Implementation of hook_form_alter().
 */
function privatemsg_extras_form_alter(&$form, $form_state, $form_id) {
  // privatemsg_extras system options
  if ($form_id == 'private_message_settings') {
    $form['privatemsg_extras'] = array(
      '#type' => 'fieldset',
      '#title' => t('Private Message Extras'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    $form['privatemsg_extras']['privatemsg_extras_test_mode'] = array(
      '#type' => 'checkbox',
      '#title' => t('Test mode'),
      '#default_value' => variable_get('privatemsg_extras_test_mode', 0),
    );
  }
  // test mode
  elseif ($form_id == 'privatemsg_new') {
    if (variable_get('privatemsg_extras_test_mode', 0))
      $form['privatemsg']['submit']['#submit'] = array('privatemsg_extras_test_submit');
  }
}

/**
 * Test mode submit
 */
function privatemsg_extras_test_submit(&$form, $form_state) {
  drupal_set_message('Message simulated succesfully');
}

/**
 * Implementation of hook_views_api().
 *
 * This tells drupal that there is Views integration file named
 * privatemsg_extras.views.inc
 */
function privatemsg_extras_views_api() {
  // Note that you can include 'path' in this array so that your views.inc
  // file can be stored in a different location.
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module','privatemsg_extras'),
  );
}

/**
* Implementation of hook_action_info().
*/
function privatemsg_extras_action_info() {
  return array(
    'privatemsg_extras_send_pvt_message_action' => array(
      'description' => t('Send a private message'),
      'type' => 'node',
      'configurable' => TRUE,
    ),
  );
}

/**
* Implementation of a Drupal action.
* Sends a private message.
*/
function privatemsg_extras_send_pvt_message_action(&$object, $context = array()) {
  privatemsg_new_thread(array(user_load($object->uid)), check_plain($context['message_subject']), check_plain($context['message_body']));
}

function privatemsg_extras_send_pvt_message_action_form($context) {
  $form['message_subject'] = array(
    '#title' => t('Message Subject'),
    '#type' => 'textfield',
    '#description' => t('Subject of the new message.'),
    '#default_value' => isset($context['message_subject']) ? $context['message_subject'] : '',
  );
  $form['message_body'] = array(
    '#title' => t('Message Body'),
    '#type' => 'textfield',
    '#description' => t('Body of the new message.'),
    '#default_value' => isset($context['message_body']) ? $context['message_body'] : '',
  );
  return $form;
}

function privatemsg_extras_send_pvt_message_action_submit($form, $form_state) {
  return array('message_subject' => $form_state['values']['message_subject'], 'message_body' => $form_state['values']['message_body']);
}

